#!/bin/bash
#
# Copyright (C) Yagnesh Raghava Yakkala. http://yagnesh.org
#    File: buildemacs
# Created: Tuesday, March 22 2011
# Licence: GPL v3 or later
#

# Instead of changing variable in here create be.conf file

SCRIPT_DIR=$(cd `dirname $BASH_SOURCE`; pwd)
cd $SCRIPT_DIR

if [ -f be.conf ]; then
    . be.conf
fi

# Use mirror instead of GNU server
# get from envronment or set it to empty.
BE_REMOTE=${BE_REMOTE:-"git://repo.or.cz/emacs.git"}
BE_CONF_FLAGS=${BE_CONF_FLAGS:-""}

. ./be-functions

function usage()
{
    cat <<EOF
USAGE:
       $0 -<Options> <args>

Options:
      -t, --tag
           build from git tag.
         latest
            Build from latest tag
         tag_name
           "tag_name" may be for example "emacs-24.1"
      -b branch_name
           build from "branch_name" (local or with remote tracking)

      -d
         build from head but enable debugging CFLAGS






Argument:
      head
           Installs from the head
EOF
    exit 4
}


if [ $# -lt 1 ]
then
    echo "${#} arguments."
    usage $0
fi


# Clone emacs repo if it is not already present
if [ ! -d emacs ]; then
    git clone $BE_REMOTE
fi
cd emacs

git_tag=""


# Parse Args
while [[ $# -gt 0 ]]; do

    case $1 in
        head|HEAD )             # last commit (rev)
            build_emacs_git_head
            break
            ;;

        -t|--tag )              # latest tag (i.e, release)
            git_tag="$git_tag $2"
            shift
            build_emacs_from_tag $git_tag
            break
            ;;


        -d )
            export CFLAGS='-g -O0'
            build_emacs_git_head
            ;;

        *)
            echo "Unknown Argument!!"
            exit 4
            ;;
    esac
    shift

done

# buildemacs ends here
