#!/bin/bash
#
# Copyright (C) Yagnesh Raghava Yakkala. http://yagnesh.org
#    File: buildemacs
# Created: Tuesday, March 22 2011
# Licence: GPL v3 or later
#

MIRROR="git://repo.or.cz/emacs.git" # Use mirror instead of GNU server
SCRIPT_DIR=$(cd `dirname $BASH_SOURCE`; pwd)
cd $SCRIPT_DIR

. ./be-functions

# Clone emacs repo if it is not already present
if [ ! -d emacs ]; then
    git clone $MIRROR
fi

cd emacs

git pull origin master

# last commit (rev)
# latest tag (i.e, release)
# or any thing argument (we just run git checkout for that)

rev=$(git rev-parse --short HEAD)
latest_tag=$(git describe --abbrev=0 --tags)

INSTALL_DIR=$HOME/local/emacs-$rev

build_emacs

# buildemacs ends here
